name: CI/CD Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Verify installed dependencies
      run: |
        npm install
        npm list --depth=0  # List installed packages to verify dependencies

    - name: Run Super-Linter
      uses: github/super-linter@v4

    - name: Install dependencies
      run: |
        npm install

    - name: Run the dev command with verbose output
      run: |
        npm run dev -- --verbose  # Run dev with more detailed logs for debugging

    - name: Run the build command
      run: |
        npm run build  # Use npm run build for production build
